version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  ignore:
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: lodash
    versions:
    - 4.17.20
